CREATE TABLE BOOKS (
    BOOK_ID INT(11) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    PUBYEAR INT(4) NOT NULL,
    PRIMARY KEY (BOOK_ID)
);

CREATE TABLE READERS (
    READER_ID INT(11) NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    PESELID VARCHAR(11) NOT NULL,
    PRIMARY KEY (READER_ID)
);

CREATE TABLE RENTS (
    RENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    BOOK_ID INT(11) NOT NULL,
    READER_ID INT(11) NOT NULL,
    RENT_DATE DATETIME NOT NULL,
    RETURN_DATE DATETIME,
    PRIMARY KEY (RENT_ID),
    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (BOOK_ID),
    FOREIGN KEY (READER_ID)
        REFERENCES READERS (READER_ID)
);

DROP TABLE RENTS;

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("John", "Smith", "83012217938");
INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Curtis", "Wilson", "75121002790");
INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Cathy", "Booker", "90112801727");
INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Marissa", "Cain", "84061908044");
INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Muriel", "Fulton", "76081409269");
COMMIT;

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Stranger", 1942);
INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("In Search of Lost Time", 1927);
INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Trial", 1925);
INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Little Prince", 1943);
INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("Man's Fate", 1933);
COMMIT;

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (1, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), null);
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (2, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), null);
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (4, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY));
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (1, 3, DATE_SUB(CURDATE(), INTERVAL 8 DAY), null);
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 3, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY));
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 4, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY));
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 5, DATE_SUB(CURDATE(), INTERVAL 8 DAY), null);
COMMIT;


