DROP FUNCTION IF EXISTS GetReaderById_v2;

DELIMITER $$

CREATE FUNCTION GetReaderById_v2(readerId INT) 
RETURNS TABLE resultTable (
	READER_ID INT(11) NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    PESELID VARCHAR(11) NOT NULL,
    PRIMARY KEY (READER_ID))
    
BEGIN
	DECLARE result VARCHAR(20) ;
    IF readerId <= 0 THEN
		SET result = 'Wrong ID';
	ELSE
		SELECT LASTNAME INTO result FROM readers WHERE READER_ID = readerId;
	END IF;
	RETURN result;
END $$

DELIMITER ;

SELECT getReaderById_v2(3);