USE KODILLA_COURSE;

-- Query plan before :
EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
EXPLAIN SELECT * FROM BOOKS WHERE TITLE = '*';

-- Create indices :
CREATE INDEX READERSNAME_INDEX ON READERS (FIRSTNAME, LASTNAME);
CREATE INDEX BOOKSTITLE_INDEX ON BOOKS (TITLE);

-- Query plan after :
EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
EXPLAIN SELECT * FROM BOOKS WHERE TITLE = '*';

-- Remove indices :
DROP INDEX READERSNAME_INDEX ON kodilla_course.readers;
DROP INDEX BOOKSTITLE_INDEX ON kodilla_course.books;