CREATE TABLE ISSUESLISTS
(
    ID		SERIAL PRIMARY KEY, 
    NAME	VARCHAR(20)
);



CREATE TABLE ISSUES
(
    ID		  SERIAL PRIMARY KEY, 
    ISSUESLIST_ID bigint unsigned NOT NULL,
    FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS (ID),
    SUMMARY	  VARCHAR(100),
    DESCRIPTION	  VARCHAR(500),
    USER_ID_ASSIGNEDTO bigint unsigned NOT NULL,
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS (ID)

);


INSERT INTO ISSUESLISTS (NAME)
VALUES ("ToDo");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("InProgress");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");

COMMIT;



INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 11", "New - Pipe broke on 5th floor", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 12", "New - Window broke on 3rd floor", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 13", "New - Chair broke on 2nd floor", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 14", "New - Fan broke on 6th floor", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 15", "New - Door broke on 1st floor", 2);

COMMIT;



INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 21", "Open - Unfinished task 21", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 22", "Open - Unfinished task 22", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 23", "Open - Unfinished task 23", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 24", "Open - Unfinished task 24", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 25", "Open - Unfinished task 25", 4);

COMMIT;


INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 31", "Closed - Task 31", 5);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 32", "Closed - Task 32", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 33", "Closed - Task 33", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 34", "Closed - Task 34", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 35", "Closed - Task 35", 1);

COMMIT;



SELECT * FROM ISSUESLISTS;
SELECT * FROM ISSUES;
SELECT * FROM USERS;

