/* Point 1 */
SELECT I.ID, I.SUMMARY, IL.NAME
FROM ISSUES I
JOIN ISSUESLISTS IL ON I.ISSUESLIST_ID = IL.ID
ORDER BY IL.ID;

/* Point 2 */
SELECT I.ID, I.SUMMARY, U.ID, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
ORDER BY U.ID;

/* Point 3 */
SELECT U.ID, U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ISSUES_NUMBER
FROM USERS U
JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0
ORDER BY U.ID;
