SELECT U.ID, U.FIRSTNAME, U.LASTNAME, COUNT(*) AS POSTS_NUMBER
FROM USERS U
JOIN POSTS P ON U.ID = P.USER_ID
GROUP BY U.ID
HAVING COUNT(*) >= 2
ORDER BY U.ID;

SELECT * FROM POSTS;
SELECT * FROM USERS;
