-- Initial settings :
SET GLOBAL event_scheduler = ON;
USE KODILLA_COURSE;

-- Create table Stats :
CREATE TABLE STATS (
	STAT_ID 	INT(11) AUTO_INCREMENT PRIMARY KEY,
	STAT_DATE 	DATETIME NOT NULL,
	STAT 		VARCHAR(20) NOT NULL,
	VALUE 		INT(11) NOT NULL
);
-- Help lines :
SELECT * FROM STATS;
DROP TABLE STATS;

-- Create View Bestsellers Count :
CREATE VIEW BESTSELLERS_COUNT AS 
	SELECT COUNT(*) AS NUMBER_OF_BESTSELLERS
	FROM BOOKS
	WHERE BESTSELLER = 1;
-- Help lines :
SELECT * FROM BESTSELLERS_COUNT;
    
-- Create Event Update Bestsellers Count :
DELIMITER $$
CREATE EVENT UPDATE_BESTSELLERS_COUNT
ON SCHEDULE EVERY 1 MINUTE
DO
	BEGIN
		  CALL UpdateBestsellers();
          INSERT INTO STATS (STAT_DATE, STAT, VALUE)
          VALUES (CURDATE(), "TOTAL BESTSELLERS", (SELECT * FROM BESTSELLERS_COUNT));
    COMMIT;
END $$
DELIMITER ;
-- Help lines :
SELECT * FROM STATS;
SHOW EVENTS;

-- Drop Event Update Bestsellers Count :
DROP EVENT UPDATE_BESTSELLERS_COUNT;
COMMIT;

